baseURL = 'https://www.cheeni.net/'
title = 'On living'
theme = 'etch'
locale = 'en-US'
timeZone = 'Asia/Kolkata'

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = 'Blessings from the father'
  dark = 'auto'
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = '/:title/'

[markup.goldmark.renderer]
  unsafe = true