baseURL = 'https://www.cheeni.net/'
title = 'On living'
theme = 'etch'
locale = 'en-US'
timeZone = 'Asia/Kolkata'

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = 'Blessings from the father'
  dark = 'auto'
  highlight = true

[permalinks]
  posts = '/:title/'

[markup.goldmark.renderer]
  unsafe = true